#docker-compose.yml

version: '3'

services:
  nginx:
    build: ./nginx
    image: chatting_nginx:latest
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    build: .
    image: chatting_web:latest
    command: daphne config.asgi:application --port 8000 --bind 0.0.0.0 -v2
    volumes:
      - static_volume:/usr/src/app/_static
      - ./:/usr/src/app/
    expose:
      - 8000
<<<<<<< HEAD
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
=======
    env_file:
      - ./.env.prod
    
  

volumes:
  
  static_volume:
>>>>>>> 36a23bea8c87b685e34147d726697d0a45db5685
